# action.yaml
name: 'Betterscan Vanta Action'
description: 'A GitHub Action that scans with Betterscan and uploads to Vanta'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Get code
      uses: actions/checkout@v3
      with:
        repository: 'marcinguy/betterscan-vanta'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run
      run: python client.py
      shell: bash
